# Generated by Django 5.1.2 on 2024-11-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_reviewfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfilm',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
